---
profiles::nrpe::checks:
  check_camus:
    ensure: present
    command: /usr/lib/nagios/plugins/check_camus.sh
  check_azkaban_job_batch_camus_duration:
    ensure: present
    command: /usr/lib/nagios/plugins/check_azkaban_job.sh duration batch camus 1800 3600
  check_azkaban_job_batch_camus_failures:
    ensure: present
    command: /usr/lib/nagios/plugins/check_azkaban_job.sh failures batch camus 1 3
  check_azkaban_job_batch_compaction_user_duration:
    ensure: present
    command: /usr/lib/nagios/plugins/check_azkaban_job.sh duration batch "compaction-user" 1800 3600
  check_azkaban_job_batch_compaction_user_failures:
    ensure: present
    command: /usr/lib/nagios/plugins/check_azkaban_job.sh failures batch "compaction-user" 1 3
  check_azkaban_job_batch_compaction_group_duration:
    ensure: present
    command: /usr/lib/nagios/plugins/check_azkaban_job.sh duration batch "compaction-group" 1800 3600
  check_azkaban_job_batch_compaction_group_failures:
    ensure: present
    command: /usr/lib/nagios/plugins/check_azkaban_job.sh failures batch "compaction-group" 1 3
  check_azkaban_job_batch_compaction_membership_duration:
    ensure: present
    command: /usr/lib/nagios/plugins/check_azkaban_job.sh duration batch "compaction-membership" 1800 3600
  check_azkaban_job_batch_compaction_membership_failures:
    ensure: present
    command: /usr/lib/nagios/plugins/check_azkaban_job.sh failures batch "compaction-membership" 1 3
  check_azkaban_job_batch_userresponses_userresponse_snapshot_creator_duration:
    ensure: present
    command: /usr/lib/nagios/plugins/check_azkaban_job.sh duration "batch-userresponses" "userresponse-snapshot-creator" 1800 3600
  check_azkaban_job_batch_userresponses_userresponse_snapshot_creator_failures:
    ensure: present
    command: /usr/lib/nagios/plugins/check_azkaban_job.sh failures "batch-userresponses" "userresponse-snapshot-creator" 1 3
  check_azkaban_job_batch_compaction_relateddata_duration:
    ensure: present
    command: /usr/lib/nagios/plugins/check_azkaban_job.sh duration batch "compaction-relateddata" 1800 3600
  check_azkaban_job_batch_compaction_relateddata_failures:
    ensure: present
    command: /usr/lib/nagios/plugins/check_azkaban_job.sh failures batch "compaction-relateddata" 1 3
collectd_plugins:
  - collectd::plugin::python

collectd::plugin::python::modulepaths: [ '/usr/share/collectd/python' ]
collectd::plugin::python::modules:
  'kafka_queue_lag':
   config: []
   script_source: '/usr/share/collectd/python/kafka_queue_lag.py'
   module_import: 'kafka_queue_lag'

azkaban::tools::speedoffsetloader::package: 'speed-offset-loader'
azkaban::tools::speedoffsetloader::version: '1.0.20-1'
azkaban::tools::speedoffsetloader::config:
  com.teradata.speedlayer.offset.loader.compactionMetaRootFolder: '/mds/facts/user/compaction/meta'
  com.teradata.speedlayer.offset.loader.compactionMetaRootFolderMembership: '/mds/facts/membership/compaction/meta'
  com.teradata.speedlayer.offset.loader.compactionMetaRootFolderUserResponse: '/mds/snapshots/userresponse/meta'
  com.teradata.speedlayer.offset.loader.compactionMetaRootFolderMobileResponse:
  com.teradata.speedlayer.offset.loader.compactionMetaRootFolderGroup: '/mds/facts/group/compaction/meta'
  com.teradata.speedlayer.offset.loader.topic: 'user'
  com.teradata.speedlayer.offset.loader.topicNameMembership: membership
  com.teradata.speedlayer.offset.loader.topicNameUserResponse: userresponse
  com.teradata.speedlayer.offset.loader.topicNameMobileResponse: mobileresponse
  com.teradata.speedlayer.offset.loader.topicNameGroup: group
  com.teradata.speedlayer.offset.loader.numberOfPartitions: 40
  com.teradata.speedlayer.offset.loader.numberOfPartitionsMembership: 10
  com.teradata.speedlayer.offset.loader.numberOfPartitionsUserResponse: 40
  com.teradata.speedlayer.offset.loader.numberOfPartitionsMobileResponse: 10
  com.teradata.speedlayer.offset.loader.numberOfPartitionsGroup: 40
  com.teradata.speedlayer.offset.loader.finishTimeLocation: '/mds/snapshots/user/meta/meta.seq'
  com.teradata.speedlayer.offset.loader.timezone: 'Europe/Berlin'
  com.teradata.speedlayer.offset.loader.topologyName:
  com.teradata.speedlayer.offset.loader.mergeWithTopologyName:
