---
java::packages: [ 'oracle-java8-installer', 'oracle-java8-set-default']
java::version: '8u161-amd64-mapp'

profiles::baseprofile::packages:
  zookeeper:
    version: 3.4.5+cdh5.14.0+136-1.cdh5.14.0.p0.47~jessie-cdh5.14.0
    pin: true

profiles::nrpe::checks:
  check_ds_u_write:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a datastore-user-write
  check_ds_u_read:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:2 -C java -a datastore-user-read
  check_ds_u_read_batch:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a datastore-user-read-batch
  check_ds_rd_write:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a datastore-relateddata-write
  check_ds_rd_read:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a datastore-relateddata-read
  check_ds_rd_read_batch:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a datastore-relateddata-read-batch
  check_ds_memb_write:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a datastore-membership-write
  check_ds_ur_write:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a datastore-userresponse-write
  check_ds_usagestats_write:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a datastore-usagestats-write
  check_ds_usagestats_read:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a datastore-usagestats-read
  check_ds_locking_srv:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a locking-service-query-server
  check_ds_schema_repo:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a schema-repository
  check_ds_se_app:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u selection-engine -c 1:1 -C java -a selection-engine-application
  check_ds_stats_collector:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a datastore-stats-collector
  check_ds_etl_server:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a etl-server
  check_ee_kafka_rest:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a KafkaRestMain
  check_ee_schema_registry:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a SchemaRegistryMain
  check_apt:
    ensure: present
    command: /usr/lib/nagios/plugins/check_apt
  check_procinfo:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procinfo.sh
  check_etl_server:
    ensure: present
    command: /usr/lib/nagios/plugins/check_etl_server.py
  check_long_running_jobs:
    ensure: present
    command: /usr/lib/nagios/plugins/check_long_running_jobs.sh
  check_ds_connect_write:
    ensure: present
    command: /usr/lib/nagios/plugins/check_procs -u root -c 1:1 -C java -a datastore-connect-write